name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Test on OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        otp_version: [23,24,25]
        os: [macos-latest]
      
    container:
      image: erlang:${{ matrix.otp_version }}
    
    steps:
      - name: Compile
        run: make
      - name: Test
        run: make test 
